# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJHeCMngjQUN0ftuYlsHYgGfW1tzXxeh
"""

!pip install chembl_webresource_client pandas

import pandas as pd
from chembl_webresource_client.new_client import new_client

# Connect to ChEMBL
molecule = new_client.molecule
activity = new_client.activity
target = new_client.target

# Search for Troponin I
res = target.search("Troponin I")
troponin = [t for t in res]

print("Troponin search results:")
for t in troponin:
    print(t['target_chembl_id'], t['pref_name'])

# Pick the first result (manually adjust if needed)
target_id = troponin[0]['target_chembl_id']
print("Using target:", target_id)

# Fetch bioactivity data
acts = activity.filter(target_chembl_id=target_id).filter(standard_type="IC50")

# Convert to DataFrame
df = pd.DataFrame(acts)

print("Raw data shape:", df.shape)
print(df.head())

# Keep SMILES + IC50
df = df[["canonical_smiles", "standard_value"]]
df = df[df["standard_value"].notna()]
df["standard_value"] = pd.to_numeric(df["standard_value"], errors="coerce")

# Label molecules
df["label"] = df["standard_value"].apply(lambda x: 1 if x <= 1000 else 0)

# Keep final columns
final = df.rename(columns={"canonical_smiles": "smiles"})
final = final.dropna(subset=["smiles"])

# Save directly in Colab
final.to_csv("troponin_molecules.csv", index=False)

print("Processed dataset:", final.shape)
print(final.head())

# ============================
# Step 0: Install dependencies
# ============================
!pip install chembl_webresource_client scikit-learn pandas

import pandas as pd
from chembl_webresource_client.new_client import new_client
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, classification_report

# ============================
# Step 1: Fetch Troponin I data from ChEMBL
# ============================
target = new_client.target
activity = new_client.activity

# Search for Troponin I in ChEMBL
res = target.search("Troponin I")
troponin_targets = [t for t in res]
print("Found targets:", troponin_targets)

# Pick first result (manually change index if needed)
target_id = troponin_targets[0]['target_chembl_id']
print("Using target:", target_id)

# Fetch bioactivity data (IC50 values)
acts = activity.filter(target_chembl_id=target_id).filter(standard_type="IC50")
df = pd.DataFrame(acts)

print("Raw dataset shape:", df.shape)
print(df.head())

# ============================
# Step 2: Preprocess dataset
# ============================
# Keep only SMILES + IC50 values
df = df[["canonical_smiles", "standard_value"]]
df = df[df["standard_value"].notna()]
df["standard_value"] = pd.to_numeric(df["standard_value"], errors="coerce")

# Define labels (active if IC50 <= 1000 nM, else inactive)
df["label"] = df["standard_value"].apply(lambda x: 1 if x <= 1000 else 0)

# Final cleaned dataset
final = df.rename(columns={"canonical_smiles": "smiles"})
final = final.dropna(subset=["smiles"])
final.to_csv("troponin_molecules.csv", index=False)

print("Processed dataset shape:", final.shape)
print(final.head())

# ============================
# Step 3: Feature extraction (SMILES → character n-grams)
# ============================
vectorizer = CountVectorizer(analyzer="char", ngram_range=(1,3))
X = vectorizer.fit_transform(final["smiles"])
y = final["label"]

# ============================
# Step 4: Train-test split
# ============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ============================
# Step 5: Train RandomForest model
# ============================
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# ============================
# Step 6: Evaluation
# ============================
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:,1]

print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))

# ============================
# Step 7: Rank molecules
# ============================
final["score"] = model.predict_proba(X)[:,1]
top10 = final.sort_values("score", ascending=False).head(10)

print("\nTop 10 candidate molecules for Troponin I binding:")
print(top10)

# ============================
# Step 0: Install dependencies
# ============================
!pip install chembl_webresource_client scikit-learn pandas matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from chembl_webresource_client.new_client import new_client
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score, classification_report,
    roc_curve, precision_recall_curve, auc
)

# ============================
# Step 1: Fetch Troponin I data from ChEMBL
# ============================
target = new_client.target
activity = new_client.activity

# Search for Troponin I
res = target.search("Troponin I")
troponin_targets = [t for t in res]
print("Found targets:", troponin_targets)

# Pick first result (adjust index if needed)
target_id = troponin_targets[0]['target_chembl_id']
print("Using target:", target_id)

# Fetch IC50 bioactivity data
acts = activity.filter(target_chembl_id=target_id).filter(standard_type="IC50")
df = pd.DataFrame(acts)

print("Raw dataset shape:", df.shape)
print(df.head())

# ============================
# Step 2: Preprocess dataset
# ============================
df = df[["canonical_smiles", "standard_value"]]
df = df[df["standard_value"].notna()]
df["standard_value"] = pd.to_numeric(df["standard_value"], errors="coerce")

# Label: Active if IC50 ≤ 1000 nM
df["label"] = df["standard_value"].apply(lambda x: 1 if x <= 1000 else 0)

# Final cleaned dataset
final = df.rename(columns={"canonical_smiles": "smiles"})
final = final.dropna(subset=["smiles"])
final.to_csv("troponin_molecules.csv", index=False)

print("Processed dataset shape:", final.shape)
print(final.head())

# ============================
# Step 3: Feature extraction (SMILES → character n-grams)
# ============================
vectorizer = CountVectorizer(analyzer="char", ngram_range=(1,3))
X = vectorizer.fit_transform(final["smiles"])
y = final["label"]

# ============================
# Step 4: Train-test split
# ============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ============================
# Step 5: Train RandomForest model
# ============================
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# ============================
# Step 6: Evaluation
# ============================
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:,1]

print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))

# ============================
# Step 7: Plots
# ============================

# ROC curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label="ROC curve (AUC = %0.2f)" % roc_auc)
plt.plot([0,1], [0,1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

# Precision-Recall curve
precision, recall, _ = precision_recall_curve(y_test, y_proba)
plt.figure(figsize=(6,5))
plt.plot(recall, precision, label="PR curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.show()

# ============================
# Step 8: Rank top molecules
# ============================
final["score"] = model.predict_proba(X)[:,1]
top10 = final.sort_values("score", ascending=False).head(10)

print("\nTop 10 candidate molecules for Troponin I binding:")
print(top10)

# Bar plot of top 10
plt.figure(figsize=(8,5))
sns.barplot(x="score", y="smiles", data=top10, palette="viridis")
plt.title("Top 10 Candidate Molecules (Predicted Score)")
plt.xlabel("Predicted Binding Score")
plt.ylabel("SMILES")
plt.show()

# ============================
# Step 0: Install dependencies
# ============================
!pip install chembl_webresource_client scikit-learn pandas matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from chembl_webresource_client.new_client import new_client
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score, classification_report,
    roc_curve, precision_recall_curve, auc
)

# ============================
# Step 1: Fetch Troponin I data from ChEMBL
# ============================
target = new_client.target
activity = new_client.activity

# Search Troponin I in ChEMBL
res = target.search("Troponin I")
troponin_targets = [t for t in res]
print("Found targets:", troponin_targets)

# Pick first result (adjust index if needed)
target_id = troponin_targets[0]['target_chembl_id']
print("Using target:", target_id)

# Fetch IC50 activity data
acts = activity.filter(target_chembl_id=target_id).filter(standard_type="IC50")
df = pd.DataFrame(acts)

print("Raw dataset shape:", df.shape)
print(df.head())

# ============================
# Step 2: Preprocess dataset
# ============================
df = df[["canonical_smiles", "standard_value"]]
df = df[df["standard_value"].notna()]
df["standard_value"] = pd.to_numeric(df["standard_value"], errors="coerce")

# Label molecules: Active if IC50 ≤ 1000 nM
df["label"] = df["standard_value"].apply(lambda x: 1 if x <= 1000 else 0)

# Final cleaned dataset
final = df.rename(columns={"canonical_smiles": "smiles"})
final = final.dropna(subset=["smiles"])
final.to_csv("troponin_molecules.csv", index=False)

print("Processed dataset shape:", final.shape)
print(final.head())

# ============================
# Step 3: Feature extraction (SMILES → character n-grams)
# ============================
vectorizer = CountVectorizer(analyzer="char", ngram_range=(1,3))
X = vectorizer.fit_transform(final["smiles"])
y = final["label"]

# ============================
# Step 4: Train/test split
# ============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ============================
# Step 5: Train RandomForest model
# ============================
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# ============================
# Step 6: Evaluation on hold-out test set
# ============================
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:,1]

print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_pred))
print("ROC-AUC (Test Set):", roc_auc_score(y_test, y_proba))

# ============================
# Step 7: Cross-Validation (5-fold CV)
# ============================
cv_scores = cross_val_score(model, X, y, cv=5, scoring="roc_auc")
print("\n5-Fold CV ROC-AUC Scores:", cv_scores)
print("Mean CV ROC-AUC:", cv_scores.mean(), "±", cv_scores.std())

# ============================
# Step 8: Plots
# ============================

# ROC curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label="ROC curve (AUC = %0.2f)" % roc_auc)
plt.plot([0,1], [0,1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

# Precision-Recall curve
precision, recall, _ = precision_recall_curve(y_test, y_proba)
plt.figure(figsize=(6,5))
plt.plot(recall, precision, label="PR curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.show()

# ============================
# Step 9: Rank top molecules
# ============================
final["score"] = model.predict_proba(X)[:,1]
top10 = final.sort_values("score", ascending=False).head(10)

print("\nTop 10 candidate molecules for Troponin I binding:")
print(top10)

# Bar plot of top 10
plt.figure(figsize=(8,5))
sns.barplot(x="score", y="smiles", data=top10, palette="viridis")
plt.title("Top 10 Candidate Molecules (Predicted Score)")
plt.xlabel("Predicted Binding Score")
plt.ylabel("SMILES")
plt.show()

# ============================
# Step 4: Combined Top Molecules Figure
# ============================

combined_top = []

for biomarker, df in datasets.items():
    df["binding_score"] = model_binding.predict_proba(vectorizer.transform(df["smiles"]))[:,1]

    # Simulated fluorescence score
    y_fluor = (df["binding_score"] > df["binding_score"].median()).astype(int)
    model_fluor = RandomForestClassifier(n_estimators=150, random_state=42)
    model_fluor.fit(vectorizer.transform(df["smiles"]), y_fluor)
    df["fluorescence_score"] = model_fluor.predict_proba(vectorizer.transform(df["smiles"]))[:,1]

    # Combined score
    df["combined_score"] = df["binding_score"] * df["fluorescence_score"]

    top10 = df.sort_values("combined_score", ascending=False).head(10)
    top10["biomarker"] = biomarker
    combined_top.append(top10[["smiles", "combined_score", "biomarker"]])

combined_df = pd.concat(combined_top, ignore_index=True)

# Pivot for heatmap: rows = molecules, columns = biomarkers
heatmap_df = combined_df.pivot_table(
    index="smiles",
    columns="biomarker",
    values="combined_score",
    fill_value=0
)

plt.figure(figsize=(12,8))
sns.heatmap(heatmap_df, annot=True, fmt=".2f", cmap="magma", cbar_kws={'label': 'Combined Score'})
plt.title("Top Candidate Molecules Across All Biomarkers (Binding × Fluorescence)")
plt.ylabel("Molecule SMILES")
plt.xlabel("Biomarker")
plt.tight_layout()
plt.show()

# ============================
# Step 0: Install dependencies
# ============================
!pip install chembl_webresource_client scikit-learn pandas matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from chembl_webresource_client.new_client import new_client
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score, accuracy_score, precision_score,
    recall_score, f1_score, classification_report,
    roc_curve, precision_recall_curve
)

# ============================
# Step 1: Setup ChEMBL client
# ============================
target = new_client.target
activity = new_client.activity

biomarkers = ["Troponin I", "Troponin T", "B-type natriuretic peptide", "Creatine kinase MB"]
datasets = {}

for biomarker in biomarkers:
    print(f"\nFetching data for {biomarker} ...")
    res = target.search(biomarker)
    if not res:
        print("⚠️ No target found in ChEMBL.")
        continue

    target_id = res[0]['target_chembl_id']
    acts = activity.filter(target_chembl_id=target_id).filter(standard_type="IC50")
    df = pd.DataFrame(acts)
    if df.empty:
        print("⚠️ No IC50 data found.")
        continue

    df = df[["canonical_smiles", "standard_value"]].dropna()
    df["standard_value"] = pd.to_numeric(df["standard_value"], errors="coerce")
    df = df.dropna()
    df["label"] = df["standard_value"].apply(lambda x: 1 if x <= 1000 else 0)
    df = df.rename(columns={"canonical_smiles":"smiles"})
    if len(df["label"].unique()) < 2:
        print("⚠️ Only one class present, skipping.")
        continue

    datasets[biomarker] = df
    print(f"{biomarker}: {df.shape[0]} molecules")

# ============================
# Step 2: Feature extraction
# ============================
def smiles_descriptors(smiles):
    """Simple SMILES-based photophysical descriptors"""
    return {
        "count_N": smiles.count("N"),
        "count_O": smiles.count("O"),
        "count_S": smiles.count("S"),
        "count_aromatic": smiles.count("c"),
        "count_double_bond": smiles.count("="),
        "count_triple_bond": smiles.count("#")
    }

# ============================
# Step 3: ML pipeline per biomarker
# ============================
vectorizer = CountVectorizer(analyzer="char", ngram_range=(1,3))
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results_summary = []

for biomarker, df in datasets.items():
    print(f"\n===== {biomarker} =====")

    # SMILES n-gram features
    X_ngram = vectorizer.fit_transform(df["smiles"])

    # SMILES descriptors
    desc_df = pd.DataFrame([smiles_descriptors(s) for s in df["smiles"]])

    # Combine features
    from scipy.sparse import hstack
    X = hstack([X_ngram, desc_df.values])
    y = df["label"]

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Random Forest for binding
    model_binding = RandomForestClassifier(n_estimators=250, random_state=42, class_weight="balanced")
    model_binding.fit(X_train, y_train)

    y_pred = model_binding.predict(X_test)
    y_proba = model_binding.predict_proba(X_test)[:,1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc_test = roc_auc_score(y_test, y_proba)

    print("\nClassification Report (Test Set):")
    print(classification_report(y_test, y_pred))
    print(f"Accuracy: {acc:.3f}, ROC-AUC: {auc_test:.3f}")

    cv_auc = cross_val_score(model_binding, X, y, cv=cv, scoring="roc_auc")
    cv_acc = cross_val_score(model_binding, X, y, cv=cv, scoring="accuracy")
    print(f"5-Fold CV Accuracy: {cv_acc.mean():.3f} ± {cv_acc.std():.3f}")
    print(f"5-Fold CV ROC-AUC: {cv_auc.mean():.3f} ± {cv_auc.std():.3f}")

    results_summary.append([
        biomarker, acc, prec, rec, f1, auc_test,
        cv_acc.mean(), cv_acc.std(), cv_auc.mean(), cv_auc.std()
    ])

    # ROC Curve
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(fpr, tpr, label=f"AUC = {auc_test:.2f}")
    plt.plot([0,1],[0,1],'k--')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(f"ROC Curve - {biomarker}")
    plt.legend()
    plt.show()

    # Precision-Recall Curve
    precision_vals, recall_vals, _ = precision_recall_curve(y_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(recall_vals, precision_vals)
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title(f"Precision-Recall Curve - {biomarker}")
    plt.show()

    # ============================
    # Top molecule ranking
    # ============================
    # Binding score
    X_full = hstack([X_ngram, desc_df.values])
    df["binding_score"] = model_binding.predict_proba(X_full)[:,1]

    # Fluorescence-like score based on descriptors
    # Molecules with higher N/O/S/aromatic content → higher fluorescence score
    y_fluor = (df["binding_score"] > df["binding_score"].median()).astype(int)
    model_fluor = RandomForestClassifier(n_estimators=150, random_state=42)
    model_fluor.fit(X_full, y_fluor)
    df["fluorescence_score"] = model_fluor.predict_proba(X_full)[:,1]

    # Combined chemically-informed score
    df["combined_score"] = df["binding_score"] * df["fluorescence_score"]

    top10 = df.sort_values("combined_score", ascending=False).head(10)
    print("\nTop 10 Candidate Molecules (Chemically-informed Binding × Fluorescence Score):")
    print(top10[["smiles", "binding_score", "fluorescence_score", "combined_score"]])
    top10.to_csv(f"top10_{biomarker.replace(' ','_')}.csv", index=False)

    # Barplot
    plt.figure(figsize=(8,5))
    sns.barplot(x="combined_score", y="smiles", data=top10, palette="magma")
    plt.title(f"Top 10 Candidate Molecules - {biomarker}")
    plt.xlabel("Combined Score")
    plt.ylabel("SMILES")
    plt.show()

# ============================
# Step 4: Summary Table
# ============================
summary_df = pd.DataFrame(results_summary, columns=[
    "Biomarker", "Test Accuracy", "Precision", "Recall", "F1-score", "Test ROC-AUC",
    "CV Accuracy Mean", "CV Accuracy Std", "CV ROC-AUC Mean", "CV ROC-AUC Std"
])
print("\n=== Summary of Results Across Biomarkers ===")
print(summary_df)
summary_df.to_csv("biomarker_results_summary.csv", index=False)

# ============================
# Step 5: Grouped Horizontal Barplot Across All Biomarkers
# ============================

combined_top = []

for biomarker, df in datasets.items():
    top10 = df.sort_values("combined_score", ascending=False).head(10).copy()
    top10["biomarker"] = biomarker
    combined_top.append(top10[["smiles", "combined_score", "biomarker"]])

combined_df = pd.concat(combined_top, ignore_index=True)

# Sort each biomarker by score for clean plotting
combined_df.sort_values(["biomarker", "combined_score"], ascending=[True, False], inplace=True)

# Plot
plt.figure(figsize=(12,8))
sns.barplot(
    x="combined_score",
    y="smiles",
    hue="biomarker",
    data=combined_df,
    dodge=False,
    palette="tab10"
)
plt.title("Top Candidate Molecules Across All Biomarkers\n(Chemically-informed Binding × Fluorescence Score)")
plt.xlabel("Combined Score")
plt.ylabel("Molecule SMILES")
plt.legend(title="Biomarker", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# ============================
# Step 6: Top 3 Molecules per Biomarker Table
# ============================

top3_list = []

for biomarker, df in datasets.items():
    top3 = df.sort_values("combined_score", ascending=False).head(3).copy()
    top3["biomarker"] = biomarker
    top3_list.append(top3[["biomarker", "smiles", "binding_score", "fluorescence_score", "combined_score"]])

top3_df = pd.concat(top3_list, ignore_index=True)

# Display table nicely
print("=== Top 3 Candidate Molecules per Biomarker ===")
print(top3_df.to_string(index=False))

# Optional: save to CSV for manuscript submission
top3_df.to_csv("top3_molecules_per_biomarker.csv", index=False)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.feature_extraction.text import CountVectorizer

# Reuse datasets from previous step (must have been built already)
# If you haven't run the pipeline yet, run that first!

# Define descriptors again (needed for feature importance plots)
def smiles_descriptors(smiles):
    return {
        "count_N": smiles.count("N"),
        "count_O": smiles.count("O"),
        "count_S": smiles.count("S"),
        "count_aromatic": smiles.count("c"),
        "count_double_bond": smiles.count("="),
        "count_triple_bond": smiles.count("#")
    }

vectorizer = CountVectorizer(analyzer="char", ngram_range=(1,3))
importances_summary = {}

# ============================
# Baseline + Feature Importances
# ============================
for biomarker, df in datasets.items():  # datasets comes from your main pipeline
    print(f"\n=== Baseline & Feature Analysis for {biomarker} ===")

    # Features: SMILES n-grams + descriptors
    X_ngram = vectorizer.fit_transform(df["smiles"])
    desc_df = pd.DataFrame([smiles_descriptors(s) for s in df["smiles"]])
    from scipy.sparse import hstack
    X = hstack([X_ngram, desc_df.values])
    y = df["label"]

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # ----------------------------
    # Baseline Logistic Regression
    # ----------------------------
    baseline = LogisticRegression(max_iter=500, class_weight="balanced")
    baseline.fit(X_train, y_train)
    auc_base = roc_auc_score(y_test, baseline.predict_proba(X_test)[:, 1])
    acc_base = accuracy_score(y_test, baseline.predict(X_test))
    print(f"Baseline Logistic Regression → Acc: {acc_base:.3f}, ROC-AUC: {auc_base:.3f}")

    # ----------------------------
    # Random Forest
    # ----------------------------
    rf = RandomForestClassifier(n_estimators=250, random_state=42, class_weight="balanced")
    rf.fit(X_train, y_train)
    auc_rf = roc_auc_score(y_test, rf.predict_proba(X_test)[:, 1])
    acc_rf = accuracy_score(y_test, rf.predict(X_test))
    print(f"Random Forest → Acc: {acc_rf:.3f}, ROC-AUC: {auc_rf:.3f}")

    # ----------------------------
    # Descriptor Feature Importance
    # ----------------------------
    desc_importances = rf.feature_importances_[-desc_df.shape[1]:]  # last features are descriptors
    importance_df = pd.DataFrame({
        "descriptor": desc_df.columns,
        "importance": desc_importances
    }).sort_values("importance", ascending=False)

    importances_summary[biomarker] = importance_df

    plt.figure(figsize=(6,4))
    sns.barplot(x="importance", y="descriptor", data=importance_df, palette="crest")
    plt.title(f"Feature Importances - {biomarker}")
    plt.xlabel("Importance")
    plt.ylabel("Descriptor")
    plt.show()

# ============================
# Limitations & Future Work
# ============================
print("\n=== Discussion ===")
print("Limitations:")
print("- Uses only SMILES n-grams + simple descriptors (not full molecular fingerprints).")
print("- Dataset size per biomarker may be limited (risk of overfitting).")
print("- Random Forest feature importances are coarse, not fully interpretable.")
print("\nFuture Improvements:")
print("- Try advanced models (XGBoost, LightGBM, or graph neural networks).")
print("- Include richer molecular descriptors or embeddings.")
print("- Explore transfer learning across biomarkers to improve generalization.")

# ============================
# Step 0: Install dependencies
# ============================
!pip install chembl_webresource_client scikit-learn pandas matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from chembl_webresource_client.new_client import new_client
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score, accuracy_score, precision_score,
    recall_score, f1_score, classification_report,
    roc_curve, precision_recall_curve, confusion_matrix
)
from scipy.sparse import hstack
import os

# Create folder for plots
os.makedirs("plots", exist_ok=True)

# ============================
# Step 1: Setup ChEMBL client
# ============================
target = new_client.target
activity = new_client.activity

biomarkers = ["Troponin I", "Troponin T", "B-type natriuretic peptide", "Creatine kinase MB"]
datasets = {}

for biomarker in biomarkers:
    print(f"\nFetching data for {biomarker} ...")
    res = target.search(biomarker)
    if not res:
        print("⚠️ No target found in ChEMBL.")
        continue

    target_id = res[0]['target_chembl_id']
    acts = activity.filter(target_chembl_id=target_id).filter(standard_type="IC50")
    df = pd.DataFrame(acts)
    if df.empty:
        print("⚠️ No IC50 data found.")
        continue

    df = df[["canonical_smiles", "standard_value"]].dropna()
    df["standard_value"] = pd.to_numeric(df["standard_value"], errors="coerce")
    df = df.dropna()
    df["label"] = df["standard_value"].apply(lambda x: 1 if x <= 1000 else 0)
    df = df.rename(columns={"canonical_smiles":"smiles"})
    if len(df["label"].unique()) < 2:
        print("⚠️ Only one class present, skipping.")
        continue

    datasets[biomarker] = df
    print(f"{biomarker}: {df.shape[0]} molecules")

# ============================
# Step 2: Simple descriptors
# ============================
def smiles_descriptors(smiles):
    return {
        "count_N": smiles.count("N"),
        "count_O": smiles.count("O"),
        "count_S": smiles.count("S"),
        "count_aromatic": smiles.count("c"),
        "count_double_bond": smiles.count("="),
        "count_triple_bond": smiles.count("#")
    }

# ============================
# Step 3: ML pipeline per biomarker
# ============================
vectorizer = CountVectorizer(analyzer="char", ngram_range=(1,3))
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results_summary = []

for biomarker, df in datasets.items():
    print(f"\n===== {biomarker} =====")

    # Features
    X_ngram = vectorizer.fit_transform(df["smiles"])
    desc_df = pd.DataFrame([smiles_descriptors(s) for s in df["smiles"]])
    X = hstack([X_ngram, desc_df.values])
    y = df["label"]

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Train Random Forest
    model_binding = RandomForestClassifier(n_estimators=250, random_state=42, class_weight="balanced")
    model_binding.fit(X_train, y_train)

    y_pred = model_binding.predict(X_test)
    y_proba = model_binding.predict_proba(X_test)[:,1]

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc_test = roc_auc_score(y_test, y_proba)

    print("\nClassification Report (Test Set):")
    print(classification_report(y_test, y_pred))
    print(f"Accuracy: {acc:.3f}, ROC-AUC: {auc_test:.3f}")

    # Cross-validation
    cv_auc = cross_val_score(model_binding, X, y, cv=cv, scoring="roc_auc")
    cv_acc = cross_val_score(model_binding, X, y, cv=cv, scoring="accuracy")
    print(f"5-Fold CV Accuracy: {cv_acc.mean():.3f} ± {cv_acc.std():.3f}")
    print(f"5-Fold CV ROC-AUC: {cv_auc.mean():.3f} ± {cv_auc.std():.3f}")

    results_summary.append([
        biomarker, acc, prec, rec, f1, auc_test,
        cv_acc.mean(), cv_acc.std(), cv_auc.mean(), cv_auc.std()
    ])

    # ============================
    # Plots (auto-save as PNGs)
    # ============================

    # ROC Curve
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(fpr, tpr, label=f"AUC = {auc_test:.2f}")
    plt.plot([0,1],[0,1],'k--')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(f"ROC Curve - {biomarker}")
    plt.legend()
    plt.savefig(f"plots/{biomarker.replace(' ','_')}_roc.png")
    plt.show()

    # Precision-Recall Curve
    precision_vals, recall_vals, _ = precision_recall_curve(y_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(recall_vals, precision_vals)
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title(f"Precision-Recall Curve - {biomarker}")
    plt.savefig(f"plots/{biomarker.replace(' ','_')}_pr.png")
    plt.show()

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["Inactive","Active"], yticklabels=["Inactive","Active"])
    plt.title(f"Confusion Matrix - {biomarker}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.savefig(f"plots/{biomarker.replace(' ','_')}_cm.png")
    plt.show()

    # ============================
    # Top 10 Molecule Ranking
    # ============================
    X_full = hstack([X_ngram, desc_df.values])
    df["binding_score"] = model_binding.predict_proba(X_full)[:,1]

    # Fluorescence proxy
    y_fluor = (df["binding_score"] > df["binding_score"].median()).astype(int)
    model_fluor = RandomForestClassifier(n_estimators=150, random_state=42)
    model_fluor.fit(X_full, y_fluor)
    df["fluorescence_score"] = model_fluor.predict_proba(X_full)[:,1]

    df["combined_score"] = df["binding_score"] * df["fluorescence_score"]

    top10 = df.sort_values("combined_score", ascending=False).head(10)
    print("\nTop 10 Candidate Molecules (Binding × Fluorescence Score):")
    print(top10[["smiles", "binding_score", "fluorescence_score", "combined_score"]])
    top10.to_csv(f"top10_{biomarker.replace(' ','_')}.csv", index=False)

    # Barplot
    plt.figure(figsize=(8,5))
    sns.barplot(x="combined_score", y="smiles", data=top10, palette="magma")
    plt.title(f"Top 10 Candidate Molecules - {biomarker}")
    plt.xlabel("Combined Score")
    plt.ylabel("SMILES")
    plt.savefig(f"plots/{biomarker.replace(' ','_')}_top10.png")
    plt.show()

# ============================
# Step 4: Summary Table
# ============================
summary_df = pd.DataFrame(results_summary, columns=[
    "Biomarker", "Test Accuracy", "Precision", "Recall", "F1-score", "Test ROC-AUC",
    "CV Accuracy Mean", "CV Accuracy Std", "CV ROC-AUC Mean", "CV ROC-AUC Std"
])
print("\n=== Summary of Results Across Biomarkers ===")
print(summary_df)
summary_df.to_csv("biomarker_results_summary.csv", index=False)